"use client";

import { useState } from "react";
import { useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import {
  BookOpen,
  CalendarDays,
  CircleAlert,
  ExternalLink,
  Radio,
  Send,
  Users,
} from "lucide-react";

import {
  configureSogpCurriculum,
  configureSogpTelegramWebhook,
  createSogpLiveClass,
  sendAdminSogpBroadcast,
} from "@/app/admin/_actions/sogp-actions";
import { issueSogpCertificate } from "@/app/admin/_actions/sogp-completion-actions";
import { getAdminSogpData } from "@/app/admin/_actions/read-actions";
import { PageHeader } from "@/components/ppc/page-header";
import { ADMIN_QUERY_KEYS } from "@/lib/admin-query";
import type { SogpBroadcastKind } from "@/lib/telegram/sogp-broadcast";

const tabs = ["Overview", "Cohorts", "Curriculum", "Enrolments", "Live classes", "Completion"] as const;
type Tab = (typeof tabs)[number];

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-NG", { day: "numeric", month: "short", year: "numeric", hour: "numeric", minute: "2-digit", timeZone: "Africa/Lagos" }).format(new Date(value));
}

function Metric({ label, value, hint, Icon }: { label: string; value: string | number; hint: string; Icon: typeof Users }) {
  return <div className="rounded-sm border border-zinc-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-zinc-500">{label}</p><p className="ppc-heading mt-1 text-xl font-semibold text-zinc-950">{value}</p></div><Icon className="size-4 text-zinc-400"/></div><p className="mt-3 text-[11px] text-zinc-500">{hint}</p></div>;
}

function BroadcastComposer() {
  const [kind, setKind] = useState<SogpBroadcastKind>("general");
  const [message, setMessage] = useState("");
  const [previewing, setPreviewing] = useState(false);
  const mutation = useMutation({
    mutationFn: () => sendAdminSogpBroadcast({ kind, message }),
    onSuccess() { setMessage(""); setPreviewing(false); },
  });
  return <section className="rounded-sm border border-zinc-200 bg-white"><div className="border-b border-zinc-100 px-4 py-3"><h2 className="ppc-heading text-sm font-semibold text-zinc-900">Channel message</h2><p className="mt-0.5 text-xs text-zinc-500">Send scheduled-style or one-off messages through SOGP bot.</p></div><div className="grid gap-3 p-4"><label className="grid gap-1 text-xs font-medium text-zinc-700">Message type<select value={kind} onChange={(event)=>{setKind(event.target.value as SogpBroadcastKind);setPreviewing(false);}} className="h-8 rounded-sm border border-zinc-200 bg-white px-2 text-xs"><option value="general">General</option><option value="preparation">Preparation</option><option value="track_release">Track release</option><option value="live_class">Live class</option></select></label><label className="grid gap-1 text-xs font-medium text-zinc-700">Message<textarea value={message} onChange={(event)=>{setMessage(event.target.value);setPreviewing(false);}} rows={6} maxLength={4096} className="resize-y rounded-sm border border-zinc-200 p-3 text-sm font-normal leading-5" placeholder="Write channel message…"/></label>{previewing?<div className="rounded-sm border border-blue-200 bg-blue-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-blue-700">Preview</p><p className="mt-2 whitespace-pre-wrap text-sm text-blue-950">{message.trim()}</p></div>:null}{mutation.error?<p className="text-xs text-rose-700">{mutation.error.message}</p>:null}{mutation.data?<p className="text-xs text-emerald-700">Sent to channel. Message ID {mutation.data.messageId}.</p>:null}<button type="button" disabled={!message.trim()||mutation.isPending} onClick={()=>previewing?mutation.mutate():setPreviewing(true)} className="inline-flex h-8 w-fit items-center gap-1.5 rounded-sm bg-[var(--color-brand-blue)] px-3 text-xs font-medium text-white disabled:opacity-50">{previewing?<Send className="size-3.5"/>:null}{mutation.isPending?"Sending":previewing?"Confirm and send":"Preview message"}</button></div></section>;
}

export function AdminSogpPage() {
  const queryClient = useQueryClient();
  const { data } = useSuspenseQuery({ queryKey: ADMIN_QUERY_KEYS.sogp, queryFn: getAdminSogpData });
  const [tab, setTab] = useState<Tab>("Overview");
  const [selectedLevelThree, setSelectedLevelThree] = useState<number[]>([]);
  const current = data.cohorts[0] ?? null;
  const currentTracks = current ? data.tracks.filter((track)=>track.cohortId===current.id) : [];
  const readyTracks = currentTracks.filter((track)=>track.ready).length;
  const curriculumMutation = useMutation({ mutationFn: ()=>{ if(!current) throw new Error("Create a cohort first."); return configureSogpCurriculum({cohortId:current.id,levelThreeLessonNumbers:selectedLevelThree});}, async onSuccess(){await queryClient.invalidateQueries({queryKey:ADMIN_QUERY_KEYS.sogp});} });
  const liveClassMutation = useMutation({ mutationFn: (formData:FormData)=>{if(!current) throw new Error("Create a cohort first."); return createSogpLiveClass({cohortId:current.id,title:String(formData.get("title")??""),startsAt:String(formData.get("startsAt")??""),endsAt:String(formData.get("endsAt")??""),youtubeLiveUrl:String(formData.get("youtubeUrl")??"")});}, async onSuccess(){await queryClient.invalidateQueries({queryKey:ADMIN_QUERY_KEYS.sogp});} });
  const certificateMutation = useMutation({ mutationFn: (enrollmentId:number)=>issueSogpCertificate({enrollmentId}), async onSuccess(){await queryClient.invalidateQueries({queryKey:ADMIN_QUERY_KEYS.sogp});} });
  const webhookMutation = useMutation({ mutationFn: configureSogpTelegramWebhook });

  return <div className="grid gap-5"><PageHeader title="SOGP" description="Cohorts, curriculum, enrolments, live classes and completion"/><nav className="flex gap-1 overflow-x-auto border-b border-zinc-200" aria-label="SOGP sections">{tabs.map((item)=><button key={item} type="button" onClick={()=>setTab(item)} className={`h-9 shrink-0 border-b-2 px-3 text-xs font-medium ${tab===item?"border-[var(--color-brand-blue)] text-zinc-950":"border-transparent text-zinc-500 hover:text-zinc-800"}`}>{item}</button>)}</nav>{currentTracks.length!==20?<div className="flex items-center gap-2 rounded-sm border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900"><CircleAlert className="size-4"/> First cohort cannot activate until all 20 tracks are content-ready.</div>:null}
  {tab==="Overview"?<div className="grid gap-4"><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Current cohort" value={current?.title??"None"} hint={current?.status.replaceAll("_"," ")??"Create cohort"} Icon={CalendarDays}/><Metric label="Enrolments" value={data.enrollments.length} hint="All SOGP enrolments" Icon={Users}/><Metric label="Active learners" value={data.enrollments.filter((item)=>item.status==="active").length} hint="Current active status" Icon={Radio}/><Metric label="Content readiness" value={`${readyTracks} / 20`} hint={currentTracks.length===20?"Curriculum configured":"Select four Level 3 tracks"} Icon={BookOpen}/></section><div className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(20rem,0.75fr)]"><section className="rounded-sm border border-zinc-200 bg-white"><div className="border-b border-zinc-100 px-4 py-3"><h2 className="ppc-heading text-sm font-semibold">{current?.title??"No cohort"}</h2></div><div className="grid gap-4 p-4 text-xs"><div className="grid gap-3 sm:grid-cols-3"><div><p className="text-zinc-500">Starts</p><p className="mt-1 font-medium text-zinc-900">{current?formatDate(current.startsAt):"—"}</p></div><div><p className="text-zinc-500">Ends</p><p className="mt-1 font-medium text-zinc-900">{current?formatDate(current.endsAt):"—"}</p></div><div><p className="text-zinc-500">Telegram-linked</p><p className="mt-1 font-medium text-zinc-900">{data.enrollments.filter((item)=>item.telegramLinkedAt).length}</p></div></div><div className="grid gap-2 border-t border-zinc-100 pt-4">{[["20-track curriculum",currentTracks.length===20],["Telegram channel",data.telegram.channelConfigured],["Bot credentials",data.telegram.botConfigured],["Bot webhook secret",data.telegram.webhookSecretConfigured],["Live classes",data.liveClasses.length>0]].map(([label,ok])=><div key={String(label)} className="flex items-center justify-between"><span>{label}</span><span className={ok?"text-emerald-700":"text-amber-700"}>{ok?"Ready":"Needs attention"}</span></div>)}</div>{webhookMutation.error?<p className="text-rose-700">{webhookMutation.error.message}</p>:null}{webhookMutation.data?<p className="text-emerald-700">Telegram webhook configured.</p>:null}<button type="button" onClick={()=>webhookMutation.mutate()} disabled={webhookMutation.isPending} className="h-8 w-fit rounded-sm border border-zinc-200 bg-white px-3 text-xs font-medium text-zinc-700 disabled:opacity-50">{webhookMutation.isPending?"Configuring":"Configure bot webhook"}</button></div></section><BroadcastComposer/></div></div>:null}
  {tab==="Cohorts"?<section className="overflow-hidden rounded-sm border border-zinc-200 bg-white"><table className="min-w-full text-left text-xs"><thead className="bg-zinc-50 text-zinc-500"><tr><th className="px-4 py-3">Cohort</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Starts</th><th className="px-4 py-3">Ends</th></tr></thead><tbody className="divide-y divide-zinc-100">{data.cohorts.map((cohort)=><tr key={cohort.id}><td className="px-4 py-3 font-medium text-zinc-900">{cohort.title}</td><td className="px-4 py-3">{cohort.status.replaceAll("_"," ")}</td><td className="px-4 py-3">{formatDate(cohort.startsAt)}</td><td className="px-4 py-3">{formatDate(cohort.endsAt)}</td></tr>)}</tbody></table></section>:null}
  {tab==="Curriculum"?<section className="grid gap-4 lg:grid-cols-[1fr_22rem]"><div className="overflow-hidden rounded-sm border border-zinc-200 bg-white"><div className="border-b border-zinc-100 px-4 py-3"><h2 className="ppc-heading text-sm font-semibold">20-track curriculum</h2><p className="mt-0.5 text-xs text-zinc-500">All Level 1 and 2 tracks are fixed. Select four ready Level 3 tracks.</p></div><div className="divide-y divide-zinc-100">{currentTracks.map((track)=><div key={track.id} className="grid grid-cols-[3rem_1fr_auto] items-center gap-3 px-4 py-3 text-xs"><span className="font-medium text-zinc-500">Day {track.dayNumber}</span><span className="text-zinc-900">L{track.levelId}.{track.lessonNumber} · {track.title}</span><span className={track.ready?"text-emerald-700":"text-amber-700"}>{track.ready?"Ready":"Missing"}</span></div>)}</div></div><aside className="rounded-sm border border-zinc-200 bg-white p-4"><h3 className="ppc-heading text-sm font-semibold">Level 3 selection</h3><div className="mt-4 grid gap-2">{data.levelThreeLessons.map((lesson)=><label key={lesson.id} className={`flex items-start gap-2 rounded-sm border p-2 text-xs ${lesson.ready?"border-zinc-200":"border-amber-200 bg-amber-50"}`}><input type="checkbox" disabled={!lesson.ready} checked={selectedLevelThree.includes(lesson.lessonNumber)} onChange={(event)=>setSelectedLevelThree((currentSelection)=>event.target.checked?[...currentSelection,lesson.lessonNumber]:currentSelection.filter((item)=>item!==lesson.lessonNumber))}/><span className="grid gap-0.5"><span className="font-medium">L3.{lesson.lessonNumber} · {lesson.title}</span><span className={lesson.ready?"text-emerald-700":"text-amber-700"}>{lesson.ready?"Content-ready":"Content missing"}</span></span></label>)}</div>{curriculumMutation.error?<p className="mt-3 text-xs text-rose-700">{curriculumMutation.error.message}</p>:null}<button type="button" disabled={selectedLevelThree.length!==4||curriculumMutation.isPending} onClick={()=>curriculumMutation.mutate()} className="mt-4 h-8 rounded-sm bg-[var(--color-brand-blue)] px-3 text-xs font-medium text-white disabled:opacity-50">{curriculumMutation.isPending?"Configuring":"Configure 20 tracks"}</button></aside></section>:null}
  {tab==="Enrolments"?<section className="overflow-x-auto rounded-sm border border-zinc-200 bg-white"><table className="min-w-full text-left text-xs"><thead className="bg-zinc-50 text-zinc-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">WhatsApp</th><th className="px-4 py-3">Country</th><th className="px-4 py-3">Telegram</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Enrolled</th></tr></thead><tbody className="divide-y divide-zinc-100">{data.enrollments.map((item)=><tr key={item.id}><td className="px-4 py-3"><p className="font-medium text-zinc-900">{item.name}</p><p className="mt-0.5 text-[10px] text-zinc-500">{item.email}</p></td><td className="px-4 py-3">{item.phone}</td><td className="px-4 py-3">{item.country}</td><td className="px-4 py-3">{item.telegramLinkedAt?"Linked":"Pending"}</td><td className="px-4 py-3">{item.status}</td><td className="px-4 py-3">{formatDate(item.createdAt)}</td></tr>)}</tbody></table></section>:null}
  {tab==="Live classes"?<section className="grid gap-4 lg:grid-cols-[1fr_22rem]"><div className="rounded-sm border border-zinc-200 bg-white"><div className="border-b border-zinc-100 px-4 py-3"><h2 className="ppc-heading text-sm font-semibold">Scheduled classes</h2></div><div className="divide-y divide-zinc-100">{data.liveClasses.length?data.liveClasses.map((item)=><div key={item.id} className="grid gap-2 px-4 py-3 text-xs sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-medium text-zinc-900">{item.title}</p><p className="mt-1 text-zinc-500">{formatDate(item.startsAt)}</p></div>{item.youtubeLiveUrl?<a href={item.youtubeLiveUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-[var(--color-brand-blue)]">YouTube <ExternalLink className="size-3"/></a>:<span className="text-amber-700">Link missing</span>}</div>):<p className="px-4 py-10 text-center text-xs text-zinc-500">No live classes scheduled.</p>}</div></div><form className="grid gap-3 rounded-sm border border-zinc-200 bg-white p-4" onSubmit={(event)=>{event.preventDefault();liveClassMutation.mutate(new FormData(event.currentTarget));}}><h3 className="ppc-heading text-sm font-semibold">Schedule class</h3><label className="grid gap-1 text-xs">Title<input name="title" required className="h-8 rounded-sm border border-zinc-200 px-2"/></label><label className="grid gap-1 text-xs">Starts<input name="startsAt" type="datetime-local" required className="h-8 rounded-sm border border-zinc-200 px-2"/></label><label className="grid gap-1 text-xs">Ends<input name="endsAt" type="datetime-local" required className="h-8 rounded-sm border border-zinc-200 px-2"/></label><label className="grid gap-1 text-xs">YouTube URL<input name="youtubeUrl" type="url" className="h-8 rounded-sm border border-zinc-200 px-2"/></label>{liveClassMutation.error?<p className="text-xs text-rose-700">{liveClassMutation.error.message}</p>:null}<button type="submit" disabled={liveClassMutation.isPending} className="h-8 rounded-sm bg-[var(--color-brand-blue)] px-3 text-xs font-medium text-white disabled:opacity-50">Schedule live class</button></form></section>:null}
  {tab==="Completion"?<section className="overflow-hidden rounded-sm border border-zinc-200 bg-white"><div className="border-b border-zinc-100 px-4 py-3"><h2 className="ppc-heading text-sm font-semibold">Completion and certificates</h2><p className="mt-0.5 text-xs text-zinc-500">{data.certificates.length} digital certificate{data.certificates.length===1?"":"s"} issued.</p></div>{certificateMutation.error?<p className="border-b border-rose-100 bg-rose-50 px-4 py-3 text-xs text-rose-700">{certificateMutation.error.message}</p>:null}<div className="divide-y divide-zinc-100">{data.enrollments.map((enrollment)=>{const issued=data.certificates.some((certificate)=>certificate.enrollmentId===enrollment.id&&!certificate.revokedAt);return <div key={enrollment.id} className="grid gap-3 px-4 py-3 text-xs sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-medium text-zinc-900">{enrollment.name}</p><p className="mt-0.5 text-zinc-500">{enrollment.email} · {enrollment.status}</p></div>{issued?<span className="text-emerald-700">Certificate issued</span>:<button type="button" disabled={certificateMutation.isPending} onClick={()=>certificateMutation.mutate(enrollment.id)} className="h-8 rounded-sm border border-zinc-200 bg-white px-3 font-medium text-zinc-700 hover:bg-zinc-50 disabled:opacity-50">Check eligibility and issue</button>}</div>;})}</div></section>:null}
  </div>;
}
